import shopImage from "../public/images/shopImage.png"

export const shopItem = [
    {
        id: 1,
        image: shopImage,
        alt: 'image',
        title: 'Apple iPhone 14 Pro',
        price: '۱۰,۰۰۰',
        description: 'آیفون 14 پرو دارای صفحه نمایش 6.1 اینچی سوپر است نمایشگر Retina XDR آیفون 14 پرو دارای صفحه نمایش 6.1 اینچی سوپر است نمایشگر',
        href: "/",
    },
    {
        id: 2,
        image: shopImage,
        alt: 'image',
        title: 'Apple iPhone 14 Pro',
        price: '۱۰,۰۰۰',
        description: 'آیفون 14 پرو دارای صفحه نمایش 6.1 اینچی سوپر است نمایشگر Retina XDR آیفون 14 پرو دارای صفحه نمایش 6.1 اینچی سوپر است نمایشگر',
        href: "/",
    },
    {
        id: 3,
        image: shopImage,
        alt: 'image',
        title: 'Apple iPhone 14 Pro',
        price: '۱۰,۰۰۰',
        description: 'آیفون 14 پرو دارای صفحه نمایش 6.1 اینچی سوپر است نمایشگر Retina XDR آیفون 14 پرو دارای صفحه نمایش 6.1 اینچی سوپر است نمایشگر',
        href: "/",
    },
    {
        id: 4,
        image: shopImage,
        alt: 'image',
        title: 'Apple iPhone 14 Pro',
        price: '۱۰,۰۰۰',
        description: 'آیفون 14 پرو دارای صفحه نمایش 6.1 اینچی سوپر است نمایشگر Retina XDR آیفون 14 پرو دارای صفحه نمایش 6.1 اینچی سوپر است نمایشگر',
        href: "/",
    },
    {
        id: 5,
        image: shopImage,
        alt: 'image',
        title: 'Apple iPhone 14 Pro',
        price: '۱۰,۰۰۰',
        description: 'آیفون 14 پرو دارای صفحه نمایش 6.1 اینچی سوپر است نمایشگر Retina XDR آیفون 14 پرو دارای صفحه نمایش 6.1 اینچی سوپر است نمایشگر',
        href: "/",
    },
    {
        id: 6,
        image: shopImage,
        alt: 'image',
        title: 'Apple iPhone 14 Pro',
        price: '۱۰,۰۰۰',
        description: 'آیفون 14 پرو دارای صفحه نمایش 6.1 اینچی سوپر است نمایشگر Retina XDR آیفون 14 پرو دارای صفحه نمایش 6.1 اینچی سوپر است نمایشگر',
        href: "/",
    },
]